# Generated by Django 2.0.6 on 2018-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='claps',
            new_name='downvote',
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
