# Generated by Django 2.0.6 on 2018-06-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_reply_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='editted',
        ),
    ]
