# Generated by Django 2.0.6 on 2018-06-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_comment_editted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
