# Generated by Django 2.0.6 on 2018-07-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20180709_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikers',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='post.Post'),
        ),
    ]
