# Generated by Django 2.0.6 on 2018-07-16 12:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20180709_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
