# Generated by Django 2.0.6 on 2018-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20180716_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Only folowers'), ('3', 'Private')], default='1', max_length=1),
        ),
    ]
