# Generated by Django 2.0.6 on 2018-07-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='share',
        ),
    ]
