# Generated by Django 2.0.6 on 2018-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_post_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_topic',
            field=models.CharField(choices=[(0, 'Tutorials'), (1, 'Latest'), (2, 'Current'), (3, 'Controversial'), (4, 'Checklists: Do'), (5, 'Listicles'), (6, 'Infographics'), (7, 'Case'), (8, 'Profiles'), (9, 'Interviews'), (10, 'from'), (11, 'Reviews'), (12, 'Comparisons'), (13, 'Video'), (14, 'MP3s'), (15, 'Resources'), (16, 'Problem'), (17, 'Share'), (18, 'A'), (19, 'Inspirational'), (20, 'Parody'), (21, 'Funny'), (22, 'Quizzes'), (23, 'Surveys'), (24, 'Local'), (25, 'Presentations'), (26, 'Frequently'), (27, 'Questions'), (28, 'Twitter'), (29, 'Contests'), (30, 'Screencasts'), (31, 'Time-Saving'), (32, 'Videos'), (33, 'Conference'), (34, 'Event'), (35, 'Top'), (36, 'Think'), (37, 'Rants'), (38, 'Pop-Culture'), (39, 'Beginner’s'), (40, '“Metrics'), (41, 'Recent'), (42, 'Free'), (43, 'Guest'), (44, 'Debates'), (45, 'Transcript'), (46, 'Myth'), (47, 'Monthly'), (48, 'Preview'), (49, 'Answer'), (50, 'Search'), (51, 'Cheatsheets'), (52, 'Criticisms'), (53, 'Share'), (54, 'Gallery'), (55, 'Talk'), (56, 'Auto-Biographical'), (57, 'Share'), (58, 'Curate'), (59, 'Holidays'), (60, 'Thankful'), (61, 'Show'), (62, 'Create'), (63, 'Share'), (64, 'Best'), (65, 'Recount'), (66, 'Aspirations'), (67, 'Best'), (68, 'Roundups'), (69, 'Get'), (70, 'Memes'), (71, 'Charity'), (72, 'Recycle Old'), (0, 'Tutorials'), (1, 'Latest'), (2, 'Current'), (3, 'Controversial'), (4, 'Checklists: Do'), (5, 'Listicles'), (6, 'Infographics'), (7, 'Case'), (8, 'Profiles'), (9, 'Interviews'), (10, 'from'), (11, 'Reviews'), (12, 'Comparisons'), (13, 'Video'), (14, 'MP3s'), (15, 'Resources'), (16, 'Problem'), (17, 'Share'), (18, 'A'), (19, 'Inspirational'), (20, 'Parody'), (21, 'Funny'), (22, 'Quizzes'), (23, 'Surveys'), (24, 'Local'), (25, 'Presentations'), (26, 'Frequently'), (27, 'Questions'), (28, 'Twitter'), (29, 'Contests'), (30, 'Screencasts'), (31, 'Time-Saving'), (32, 'Videos'), (33, 'Conference'), (34, 'Event'), (35, 'Top'), (36, 'Think'), (37, 'Rants'), (38, 'Pop-Culture'), (39, 'Beginner’s'), (40, '“Metrics'), (41, 'Recent'), (42, 'Free'), (43, 'Guest'), (44, 'Debates'), (45, 'Transcript'), (46, 'Myth'), (47, 'Monthly'), (48, 'Preview'), (49, 'Answer'), (50, 'Search'), (51, 'Cheatsheets'), (52, 'Criticisms'), (53, 'Share'), (54, 'Gallery'), (55, 'Talk'), (56, 'Auto-Biographical'), (57, 'Share'), (58, 'Curate'), (59, 'Holidays'), (60, 'Thankful'), (61, 'Show'), (62, 'Create'), (63, 'Share'), (64, 'Best'), (65, 'Recount'), (66, 'Aspirations'), (67, 'Best'), (68, 'Roundups'), (69, 'Get'), (70, 'Memes'), (71, 'Charity'), (72, 'Recycle Old'), (73, 'Non Categorized')], default=73, max_length=1),
        ),
    ]
