# Generated by Django 2.0.6 on 2018-08-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_post_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.CharField(default='personal', help_text='Tags seperated with a space', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_topic',
            field=models.CharField(choices=[('0', 'PERSONAL'), ('1', 'FUTURE'), ('2', 'CULTURE'), ('3', 'TECH'), ('4', 'ENTREPRENEURSHIP'), ('5', 'SELF'), ('6', 'POLITICS'), ('7', 'DESIGN'), ('8', 'SCIENCE'), ('9', 'POPULAR')], default='0', max_length=1),
        ),
    ]
