# Generated by Django 2.0.6 on 2018-07-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20180728_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='post.Topic'),
        ),
    ]
