# Generated by Django 2.0.6 on 2018-07-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20180728_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
    ]
