# Generated by Django 2.0.6 on 2018-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20180805_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_tags',
            field=models.CharField(help_text='Tags seperated with a space', max_length=255),
        ),
    ]
