# Generated by Django 2.0.6 on 2018-06-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
