# Generated by Django 2.0.6 on 2018-07-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiy', '0002_notice_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('1', 'Post'), ('2', 'Comment'), ('3', 'Reply'), ('4', 'Follow')], max_length=1),
        ),
    ]
