# Generated by Django 2.0.6 on 2018-06-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='ProfilePic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
