# Generated by Django 2.0.6 on 2018-06-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180611_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='following',
        ),
    ]
