# Generated by Django 2.0.6 on 2018-06-13 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userextend',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
