# Generated by Django 2.0.6 on 2018-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180613_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
