# Generated by Django 2.0.6 on 2018-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180616_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='protected',
            field=models.CharField(choices=[('1', 'only followers'), ('2', 'no one allowed'), ('3', 'everyone')], default='1', max_length=1),
        ),
    ]
