# Generated by Django 2.0.6 on 2018-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_userextend_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='protected',
            field=models.CharField(choices=[('1', 'No One allowed'), ('2', 'only followers'), ('3', 'everyone')], default='1', max_length=1),
        ),
    ]
