# Generated by Django 2.0.6 on 2018-06-17 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0012_auto_20180617_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePics',
            new_name='Images',
        ),
    ]
