# Generated by Django 2.0.6 on 2018-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20180617_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='img_type',
            field=models.CharField(choices=[('0', 'Profile Pic'), ('1', 'Post Pic'), ('2', 'Article Pic')], default='1', max_length=1),
        ),
    ]
