# Generated by Django 2.0.6 on 2018-07-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20180716_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='Profile_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.Images'),
        ),
    ]
