# Generated by Django 2.0.6 on 2018-07-16 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20180716_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
