# Generated by Django 2.0.6 on 2018-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20180716_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='Profile_pic',
        ),
        migrations.AlterField(
            model_name='images',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='registration.UserExtend'),
        ),
    ]
