# Generated by Django 2.0.6 on 2018-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20180716_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
