# Generated by Django 2.0.6 on 2018-07-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_images_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=1),
        ),
    ]
