# Generated by Django 2.0.6 on 2018-07-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20180719_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
