# Generated by Django 2.0.6 on 2018-07-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_userextend_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
    ]
