# Generated by Django 2.0.6 on 2018-07-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_auto_20180728_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='avatar',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
