# Generated by Django 2.0.6 on 2018-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_userextend_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='avatar',
            field=models.SmallIntegerField(default=1),
        ),
    ]
