# Generated by Django 2.0.6 on 2018-07-31 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0031_auto_20180728_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='fusers',
        ),
        migrations.AddField(
            model_name='userextend',
            name='follower',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userextend',
            name='following',
            field=models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
