# Generated by Django 2.0.6 on 2018-07-31 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_auto_20180731_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook url'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='twitter url'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
